<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="title" align="center">-- Filter --</td>
  </tr>
  <tr>
    <td class="tableTit1" align="center">Filtered grid</td>
  </tr>
  <tr>
  	<td class="tableCarga" align="center">
  		<div align="left" class="code">
  			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:'Arial Black'; font-size:10.0pt; color:navy; ">Constructor:</span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:#660000; ">&nbsp;</span></p>
			<p class="MsoNormal" style="margin-left:9.0pt;text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:#660000; ">$filteredGrid </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">= AjaxGrid::create(</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;filteredGrid&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">,</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">new </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">DBQueryDescriptor(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;city&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">,</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;ID&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">,</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;Name&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;CountryCode&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;District&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">))</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ),</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;ID&quot; </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">=&gt; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">new </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">ColumnMapped(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;%s&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;city.ID&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">),</span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">true</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">,</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">'5%'</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">),</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;Name&quot; </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">=&gt; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">new </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">ColumnMapped(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;%s&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;city.Name&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">), </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">true</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">),</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;Country Code&quot; </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">=&gt; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">new </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">ColumnMapped(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;%s&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;city.CountryCode&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">), </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">true</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, NULL,</span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">true</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">),</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;District&quot; </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">=&gt; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">new </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">ColumnMapped(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;%s&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;city.District&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">), </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">true</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, NULL, </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">true</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">)</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ), </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">false</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">'1'</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">, </span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;Country Code&quot; </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">=&gt; </span><span style="font-family:Verdana; font-size:8.0pt; color:blue; ">array</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">(</span><span style="font-family:Verdana; font-size:8.0pt; color:#008200; ">&quot;District&quot;</span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">))</span><span style="font-family:Verdana; font-size:8.0pt; "> </span></p>
			<p class="MsoNormal" style="margin-left:9.0pt;text-autospace:none;"><span style="font-family:Verdana; font-size:8.0pt; color:black; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:Verdana; font-size:8.0pt; color:black; ">);</span><span style="font-family:Verdana; font-size:8.0pt; color:#660000; "> </span>
		</div>
  	</td>
  </tr>
  <tr>
    <td class="tableCarga" align="center">
		
		<div><?php echo $filteredGrid->getHtml(); ?></div>
		
    </td>
  </tr>
</table>